# Generated by Django 4.2.25 on 2025-10-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tipologia',
            field=models.CharField(choices=[('Ambulatoriale', 'Ambulatoriale'), ('Ricoverato', 'Ricoverato')], default='Ambulatoriale', max_length=100),
        ),
    ]
