# Generated by Django 4.2.25 on 2025-10-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_tipologia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='sesso',
        ),
        migrations.AddField(
            model_name='patient',
            name='genere',
            field=models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
